project:
  type: book
  output-dir: docs
    

book:
  title: "Peace and Trust Progress Journal"
  repo-url: https://github.com/pjournal/gh-pages-quarto-template
  chapters:
    - index.qmd
    - assignment1.qmd
    - project/agriculture.qmd
    - project/agriculture_eda.qmd
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

