---
title: "Group Project: Agriculture in Turkey"
date: "19 November 2022"
format:
  html:
    toc: true
    toc-depth: 3
    toc-float: true
    code-fold: true
    code-summary: "Code"
    number-sections: false
---

```{=html}
<style>
    body { 
    font-family: Calibri;
    text-align: justify;
    font-size: 11pt;
    div.hidecode + pre {display: none}
    }
</style>
```
::: hidecode
```{r setup, output=FALSE,echo=FALSE,warning = FALSE}
knitr::opts_chunk$set(warning = FALSE)
Sys.setlocale(locale = "en_US.UTF-8")
options(dplyr.summarise.inform = FALSE)
```
:::

## DATA DESCRIPTION

## PREPROCESS

Call necessary libraries

```{r call_libraries, warning=  FALSE,  message = FALSE}
#install.packages("readxl")
library(readxl)
library(lubridate)
library(dplyr)
library(tidyverse)
library(ggplot2)
```

Load the TUIK data sets

```{r load_data, warning = FALSE}
tarim_raw = read_excel("data//tarım.xlsx")
tahil_raw = read_excel("data//tahıl.xlsx")
sebze_raw = read_excel("data//sebze.xlsx")
meyve_raw = read_excel("data//meyve.xlsx")
```

Fixing the column names

```{r fixing_column_names, warning = FALSE}
new_cols <- c("province","year","decare")
colnames(tarim_raw) <- new_cols
new_cols <- c("vegetable_type","province","year","production")
colnames(sebze_raw) <- new_cols
new_cols <- c("grain_type","province","year","production")
colnames(tahil_raw) <- new_cols
```

Seperating Column

```{r}
tahil_v1 <- separate(data = tahil_raw, col = grain_type, into = c("main_type", "product_type"), sep = "ve")

tahil <- separate(data = tahil_v1, col = product_type, into = c("product_type", "unit"), sep = "-")

sebze_v1 <- separate(data = sebze_raw, col = vegetable_type, into = c("main_type", "product_type"), sep = "ve")

sebze <- separate(data = sebze_v1, col = product_type, into = c("product_type", "unit"), sep = "-")

meyve_v1 <- separate(data = meyve_raw, col = Tür, into = c("main_type", "product_type"), sep = " ve ")

meyve <- separate(data = meyve_v1, col = product_type, into = c("product_type", "unit"), sep = "-")

```

```{r}
head(tarim_raw)
```

```{r}
head(tahil)
```

```{r}
head(sebze)
```

```{r}
head(meyve)
```

```{r}
print("hello world")
```
